name: Send Slack message to channel

description: 'Send Slack message to channel'

inputs:
  token:
    description: 'Slack bot token'
    required: true
  channel_id:
    description: 'Slack channel id'
    required: true
  text:
    description: 'Slack message'
    required: true
  update:
    description: 'Update previous Slack message with ts identifier'
    required: false
    default: ''
  reply:
    description: 'Reply previous Slack message with ts indentifier'
    required: false
    default: ''
  status_msg:
    description: 'Status message when not using the status file'
    required: false
    default: ''
  status_file:
    description: 'Status file from which to retrieve the statuses'
    required: false
    default: slack_status.txt

outputs:
  update:
    description: "Slack update ts"
    value: ${{ steps.slack.outputs.ts }}

runs:
  using: "composite"
  continue-on-error: true
  steps:
    - id: pre
      shell: bash
      env:
        status_msg: ${{ inputs.status_msg }}
        status_file: ${{ inputs.status_file }}
        text: ${{ inputs.text }}
      run: |
        set -x
        echo "UPPER_TEXT=$(echo "$text" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT
        
        if [[ "$status_msg" == "" ]]; then
          awk '{printf "%s\\n", $0}' $status_file > slack_status_formatted.txt
          echo "STATUS_OUTPUT=$(cat slack_status_formatted.txt)" >> $GITHUB_OUTPUT

          status_lower=$(cat slack_status_formatted.txt | tr '[:upper:]' '[:lower:]')
          if grep -q failed $status_file; then
            echo "COLOR=ff0000" >> $GITHUB_OUTPUT
          else
            echo "COLOR=90ee90" >> $GITHUB_OUTPUT
          fi
        else
          echo "STATUS_OUTPUT=$status_msg" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true

    - id: slack
      uses: slackapi/slack-github-action@v1.26.0
      if: steps.pre.outputs.STATUS_OUTPUT != ''
      with:
        channel-id: ${{ inputs.channel_id }}
        update-ts: ${{ inputs.update }}
        payload: |
          {
            "text": "[${{ steps.pre.outputs.UPPER_TEXT }}",
            "attachments": [
              {
                "color": "${{ steps.pre.outputs.COLOR }}",
                "fields": [
                  {
                    "short": true,
                    "value": "${{ steps.pre.outputs.STATUS_OUTPUT }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.token }}
      continue-on-error: true

    - uses: slackapi/slack-github-action@v1.26.0
      if: inputs.reply != ''
      with:
        channel-id: ${{ inputs.channel_id }}
        update-ts: ${{ inputs.update }}
        payload: |
          {
            "text": "[${{ inputs.text }}",
            "thread_ts": "${{ inputs.reply }}"
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.token }}
      continue-on-error: true
