name: Send Slack message to channel

description: 'Send Slack message to channel'

inputs:
  token:
    description: 'Slack bot token'
    required: true
  channel_id:
    description: 'Slack channel id'
    required: true
  title:
    description: 'Slack message'
    required: true
  update:
    description: 'Update previous Slack message with ts identifier'
    required: false
    default: ''
  reply:
    description: 'Reply previous Slack message with ts indentifier'
    required: false
    default: ''
  status_msg:
    description: 'Status message when not using the status file'
    required: false
    default: ''
  status_file:
    description: 'Status file from which to retrieve the statuses'
    required: false
    default: slack_status.txt
  status_file_update:
    description: 'Status file update command'
    required: false
    default: ""

outputs:
  update:
    description: "Slack update ts"
    value: ${{ steps.slack.outputs.ts }}

runs:
  using: "composite"
  steps:
    - id: pre
      shell: bash
      env:
        status_msg: ${{ inputs.status_msg }}
        status_file: ${{ inputs.status_file }}
        status_file_update: ${{ inputs.status_file_update }}
        title: ${{ inputs.title }}
      run: |
        set -x
        if [[ "$status_msg" == "" ]]; then
          if [[ "$status_file_update" != "" ]]; then
            eval "$status_file_update"
          fi
             
          sed -i 's/- success/- _SUCCESS_ :white_check_mark:/g' $status_file
          sed -i 's/- failure/- _FAILURE_ :x:/g' $status_file
          sed -i 's/- canceled/- _CANCELED_ :octagonal_sign:/g' $status_file
          sed -i 's/- skipped/- _SKIPPED_ :no_entry:/g' $status_file
          sed -i 's/- pending/- _PENDING_ :hourglass_flowing_sand:/g' $status_file

          awk '{printf "%s\\n", $0}' $status_file > slack_status_formatted.txt
          echo "STATUS_OUTPUT=$(cat slack_status_formatted.txt)" >> $GITHUB_OUTPUT

          if grep -q "\*~~~~WORKFLOW~~~~\* - _RUNNING_" $status_file; then
            echo "COLOR=ffff00" >> $GITHUB_OUTPUT 
          elif grep -q "\*~~~~WORKFLOW~~~~\* - _FAILED_" $status_file; then
            echo "COLOR=ff0000" >> $GITHUB_OUTPUT
          else
            echo "COLOR=90ee90" >> $GITHUB_OUTPUT
          fi
        else
          {
            echo 'STATUS_OUTPUT<<EOF'
            echo $status_msg
            echo EOF
          } >> "$GITHUB_OUTPUT"
        
        fi
      continue-on-error: true

    - id: slack
      uses: slackapi/slack-github-action@v1.26.0
      if: steps.pre.outputs.STATUS_OUTPUT != '' && inputs.status_msg == ''
      with:
        channel-id: ${{ inputs.channel_id }}
        update-ts: ${{ inputs.update }}
        payload: |
          {
            "attachments": [
              {
                "title": "[${{ inputs.title }}]",
                "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "color": "${{ steps.pre.outputs.COLOR }}",
                "fields": [
                  {
                    "short": false,
                    "value": "${{ steps.pre.outputs.STATUS_OUTPUT }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.token }}
      continue-on-error: true

    - name: Format message
      id: formatmsg
      if: inputs.status_msg != ''
      shell: bash
      run: |
        FORMATED_MSG="$(echo ${{ toJSON(inputs.status_msg) }} | sed -z 's/\"//g')"
        echo "formated_msg=<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ toJSON(inputs.status_msg) }}>" >> $GITHUB_OUTPUT

    - id: briefslack
      uses: slackapi/slack-github-action@v1.26.0
      if: inputs.status_msg != ''
      with:
        channel-id: ${{ inputs.channel_id }}
        update-ts: ${{ inputs.update }}
        payload: |
          {
            "type": "mrkdwn",
            "text": "${{ steps.formatmsg.outputs.formated_msg }}"
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.token }}
      continue-on-error: true

    - uses: slackapi/slack-github-action@v1.26.0
      if: inputs.reply != ''
      with:
        channel-id: ${{ inputs.channel_id }}
        update-ts: ${{ inputs.update }}
        payload: |
          {
            "text": "[${{ inputs.title }}",
            "thread_ts": "${{ inputs.reply }}"
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.token }}
      continue-on-error: true
