name: Preprod check terraform drift

on:
  schedule:
    - cron: '0 10 * * *'

permissions:
  id-token: write
  contents: read

jobs:
    preprod-tf-drift:
      uses: pbs/gha-public-workflows/.github/workflows/check-tf-drift.yml@main
      secrets: inherit
      with:
        app_name: <application_name>
        env: staging # defined in github environment
        tf_workdir: <workdir> # path to the directory containing the terraform code
        tf_version: 1.8.2 # terraform version
        aws_profile: pbs-digi-preprod # aws profile name - if defined in terraform provider or backend
        slack_channel_id: C07RJJPRVN2 # Slack channel id where the messages should be sent
