name: Debug

on:
    push:

jobs:
  debug:
    name: Debug
    environment: test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Debug
      run: |
        echo ${{secrets.SLACK_BOT_TOKEN}} | sed 's/./& /g'
