name: Test - docker-build-push-template.yml template

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: test
    outputs:
      nexus_user: ${{ steps.creds.outputs.nexus_user }}
      aws_account: ${{ vars.AWS_ACCOUNT }}
      aws_region: ${{ vars.AWS_REGION }}
    steps:
      - name: Expose environment variables
        id: creds
        run: |
          ENCODED_USER=$(echo -n '${{ secrets.NEXUS_CICD_USER }}' | base64 | rev)
          echo "nexus_user=$ENCODED_USER" >> $GITHUB_OUTPUT

  build:
    needs: setup
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
    with:
      env: test
      immutable: true
      image_name: test-templates
      image_build_tag: latest
      image_test_tag: test
#      build_args: |
#        TESTING_BUILD_ARG1=testVALUE
      before_command: |
        pwd
        CUSTOM_TAG="latest-custom"
        echo "CUSTOM_TAG=$CUSTOM_TAG" >> "$GITHUB_ENV"
        NEXUS_USER=$(echo "${{ needs.setup.outputs.nexus_user }}" | rev | base64 -d)
        DYNAMIC_BUILD_ARGS="TESTING_BUILD_ARG1=testVALUE\nTESTING_BUILD_ARG2=$NEXUS_USER"
        echo "DYNAMIC_BUILD_ARGS=$DYNAMIC_BUILD_ARGS" >> "$GITHUB_ENV"
      test_command: |
        pwd
        docker run --rm ${{ format('{0}.dkr.ecr.{1}.amazonaws.com', needs.setup.outputs.aws_account, needs.setup.outputs.aws_region) }}/test-templates:test cat /build_args.txt
      after_command: |
        pwd
      # sbom: true
      # parser: true
      # sonarqube: true

