name: Test - docker-build-push-template.yml template

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    build-test-push:
      uses: ./.github/workflows/docker-build-push.yml
      secrets: inherit
      with:
        env: test
        immutable: true
        image_name: test-templates
        image_build_tag: latest
        image_test_tag: test
        before_command: |
          pwd
          CUSTOM_TAG="latest-custom"
          echo "CUSTOM_TAG=$CUSTOM_TAG" >> "$GITHUB_ENV"
        test_command: |
          pwd
        after_command: |
          pwd
        # sbom: true
        # parser: true
        # sonarqube: true
