name: Test - docker-build-push-template.yml template

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    build:
      uses: ./.github/workflows/docker-build-push.yml
      secrets: inherit
      with:
        env: test
        immutable: false
        image_name: test-templates
        image_build_tag: latest
        image_test_tag: test
        build_args: |
          TESTING_BUILD_ARG1=testVALUE
          TESTING_BUILD_ARG2=${{ vars.SLACK_CHANNEL_ID }}
        before_command: |
          pwd
          CUSTOM_TAG="latest-custom"
          echo "CUSTOM_TAG=$CUSTOM_TAG" >> "$GITHUB_ENV"
        test_command: |
          pwd
        after_command: |
          pwd
          docker run -it --rm test-image sh -c "cat /build_args.txt"
        # sbom: true
        # parser: true
        # sonarqube: true
