name: Test docker-build-push-template.yml template

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    build-test-push:
      uses: ./.github/workflows/docker-build-push-template.yml
      secrets: inherit
      with:
        env: test
        image_name: test-templates
        image_build_tag: latest
        image_test_tag: test
