name: Template - Run Commands

on:
  workflow_call:
    inputs:
      env:
        type: string
        description: 'Environment'
        required: true
      name:
        type: string
        description: 'Command name'
        required: true
      before_command:
        type: string
        description: '(Optional) Command to prepare the environment'
        required: false
        default: ''
      command:
        type: string
        description: 'Command to run'
        required: false
        default: ''
      after_command:
        type: string
        description: '(Optional) Command to teardown the environment'
        required: false
        default: ''
      assume_aws_role:
        type: boolean
        description: 'Assume AWS role'
        required: false
        default: true
      ecr_login:
        type: boolean
        description: 'Login to ECR'
        required: false
        default: true
      parser:
        type: boolean
        description: 'Publish test results using JUnit Parser'
        required: false
        default: false
      report_paths:
        type: string
        description: 'JUnit Parser report paths'
        required: false
        default: 'outdist/*.xml'

env:
  APP_NAME: ${{ vars.APP_NAME }}
  SLACK_TITLE: "RUN COMMAND ${{ inputs.name }} -  ${{ vars.APP_NAME }} -> ${{ inputs.env }}"


jobs:
  run-commands:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      # Get code, permissions and set environment
      - name: Code Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      # Slack preparation
      - name: Slack Status file
        env:
          BEFORE_COMMAND: ${{ inputs.before_command }}
          COMMAND: ${{ inputs.command }}
          AFTER_COMMAND: ${{ inputs.after_command }}
        run: |
          echo "*Code Checkout* - _SUCCESS_ :white_check_mark: " > slack_status.txt
          echo "*AWS Assume Role* - $([[ \"${{ inputs.assume_aws_role }}\" == \"true\" ]] && echo pending :hourglass_flowing_sand: || echo skipped :no_entry:)" >> slack_status.txt
          echo "*AWS ECR Login* - $([[ \"${{ inputs.ecr_login }}\" == \"true\" ]] && echo pending :hourglass_flowing_sand: || echo skipped :no_entry:)" >> slack_status.txt
          echo "*Preparation Command* - $([[ -n \"$BEFORE_COMMAND\" ]] && echo pending :hourglass_flowing_sand: || echo skipped :no_entry:)" >> slack_status.txt
          echo "*Run Command ${{ inputs.name }}* - $([[ -n \"$COMMAND\" ]] && echo pending :hourglass_flowing_sand: || echo skipped :no_entry:)" >> slack_status.txt
          echo "*Teardown Command* - $([[ -n \"$AFTER_COMMAND\" ]] && echo pending :hourglass_flowing_sand: || echo skipped :no_entry:)" >> slack_status.txt
          echo "*Parsing Results* - $([[ \"${{ inputs.parser }}\" == true ]] && echo pending :hourglass_flowing_sand: || echo skipped :no_entry:)" >> slack_status.txt
          echo "*>>>>>WORKFLOW<<<<<* - _RUNNING_" >> slack_status.txt

      # Slack Workflow start
      - name: Slack Workflow start
        uses: pbs/gha-public-workflows/.github/actions/slack-message@slack_msg_improvement
        if: vars.SLACK_CHANNEL_ID != ''
        id: slack
        with:
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          title: ${{ env.SLACK_TITLE }}

      - name: Assume AWS role
        if: inputs.assume_aws_role == true
        uses: aws-actions/configure-aws-credentials@v4
        id: aws-assume-role
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/service/${{ vars.AWS_OIDC_ROLE }}

      - name: AWS ECR Login
        if: inputs.ecr_login == true
        uses: aws-actions/amazon-ecr-login@v2
        id: aws-ecr-login

      # Preparation Command
      - name: Preparation Command
        if: inputs.before_command != ''
        id: before-command
        run: ${{ inputs.before_command }}
      
      - name: Update Slack
        uses: pbs/gha-public-workflows/.github/actions/slack-message@slack_msg_improvement
        if: always() && vars.SLACK_CHANNEL_ID != ''
        with:
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          title: ${{ env.SLACK_TITLE }}
          update: ${{ steps.slack.outputs.update }}
          status_file_update: |
            sed -i 's|\*AWS Assume Role\* - .*|\*AWS Assume Role\* - ${{ steps.aws-assume-role.outcome }}|' slack_status.txt;
            sed -i 's|\*AWS ECR Login\* - .*|\*AWS ECR Login\* - ${{ steps.aws-ecr-login.outcome }}|' slack_status.txt;
            sed -i 's|\*Preparation Command\* - .*|\*Preparation Command\* - ${{ steps.before-command.outcome }}|' slack_status.txt


      # Run Command
      - name: Run Command ${{ inputs.name }}
        if: inputs.command != ''
        id: command
        run: ${{ inputs.command }}

      - name: Update Slack
        uses: pbs/gha-public-workflows/.github/actions/slack-message@slack_msg_improvement
        if: always() && vars.SLACK_CHANNEL_ID != ''
        with:
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          title: ${{ env.SLACK_TITLE }}
          update: ${{ steps.slack.outputs.update }}
          status_file_update: |
            sed -i 's|\*Run Command ${{ inputs.name }}\* - .*|\*Run Command ${{ inputs.name }}\* - ${{ steps.command.outcome }}|' slack_status.txt


      # Teardown Command
      - name: Teardown Command
        if: always() && inputs.after_command != ''
        id: after-command
        run: ${{ inputs.after_command }}
        continue-on-error: true

      - name: Update Slack
        uses: pbs/gha-public-workflows/.github/actions/slack-message@slack_msg_improvement
        if: always() && inputs.after_command != '' && vars.SLACK_CHANNEL_ID != ''
        with:
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          title: ${{ env.SLACK_TITLE }}
          update: ${{ steps.slack.outputs.update }}
          status_file_update: |
            sed -i 's|\*Teardown Command\* - .*|\*Teardown Command\* - ${{ steps.after-command.outcome }}|' slack_status.txt

      - name: JUnit Parser
        if: inputs.parser == true
        uses: mikepenz/action-junit-report@v4
        id: parser
        with:
          report_paths: ${{ inputs.report_paths }}
      
      - name: Update Slack
        uses: pbs/gha-public-workflows/.github/actions/slack-message@slack_msg_improvement
        if: always() && inputs.parser == true && vars.SLACK_CHANNEL_ID != ''
        with:
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          title: ${{ env.SLACK_TITLE }}
          update: ${{ steps.slack.outputs.update }}
          status_file_update: |
            sed -i 's|\*Parsing Results\* - .*|\*Parsing Results\* - ${{ steps.parser.outcome }}|' slack_status.txt

      # Job End Status
      - name: Set job end status
        if: success() || failure()
        id: end-status
        run: |
          if [[ "${{ steps.before-command.outcome }}" == "failure" ]]; then
            echo "::error step=before-command::Failed to run preparation command!"; exit 1
          fi

          if [[ "${{ steps.command.outcome }}" == "failure" ]]; then
            echo "::error step=build-image::Failed to run the command!"; exit 2
          fi

          if [[ "${{ steps.after-command.outcome }}" == "failure" ]]; then
            echo "::warning step=after-command::Failed to run teardown command!"; exit 0
          fi

      - name: Update Slack
        uses: pbs/gha-public-workflows/.github/actions/slack-message@slack_msg_improvement
        if: always() && inputs.after_command != '' && vars.SLACK_CHANNEL_ID != ''
        env:
          WF_STATUS: ${{ steps.end-status.outcome }}
        with:
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          title: ${{ env.SLACK_TITLE }}
          update: ${{ steps.slack.outputs.update }}
          status_file_update: |
            sed -i "s|\*>>>>>WORKFLOW<<<<<\* - .*|\*>>>>>WORKFLOW<<<<<\* - $([[ \"${{ steps.end-status.outcome }}\" == \"success\" ]] && echo _PASSED_ || echo _FAILED_)|" slack_status.txt
