name: Test - run-commands-template.yml template

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    run-commands:
      uses: ./.github/workflows/run-commands.yml
      secrets: inherit
      with:
        env: test
        name: testing123
        before_command: pwd
        command: |
          pwd
        after_command: |
          pwd
        parser: true
        brief_slack_msg: '[run-commands] - test :'

  # Brief Slack Workflow status
    slack-brief:
      if: ${{ always() }}
      needs: [  run-commands ]
      runs-on: ubuntu-latest
      environment: test
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: slack-artifact
            path: slack

        - id: slackmsg
          run: |
            {
              echo 'BRIEF_MSG<<EOF'
              cat slack/brief_status.txt
              echo
              echo EOF
            } >> "$GITHUB_OUTPUT"

        - name: Brief slack message
          uses: pbs/gha-public-workflows/.github/actions/slack-message@CAT-24618_brief_slack_msg_v2
          with:
            channel_id: ${{ vars.SLACK_CHANNEL_ID }}
            token: ${{ secrets.SLACK_BOT_TOKEN }}
            title: "dummy"
            status_msg: ${{ steps.slackmsg.outputs.BRIEF_MSG }}
