name: GitHub TruffleHog Action Test Reusable Remote Workflow
run-name: ${{ github.actor }} running remote workflow

on:
  workflow_dispatch:

jobs:
    secrets-scanning:
      uses: ./.github/workflows/secrets-scanning.yml
      permissions:
        contents: read
        id-token: write
        issues: write
        pull-requests: write
    job1:
      needs: secrets-scanning
      runs-on: ubuntu-latest
      steps:
        - name: job1step1
          run: echo "Hello world!"
    job2:
      needs: secrets-scanning
      runs-on: ubuntu-latest
      steps:
        - name: job2step1
          run: echo "Hello world!"
